### ISSUE TITLE
pip install torch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0报错问题

### ISSUE THREAD

**Issue by hjdsd** [datawhalechina/joyrl#4]
在window上配环境时，pip install torch==1.10.0 torchvision==0.11.1 torchaudio==0.10.0报错，改为pip install torch==1.10.0 torchvision==0.11.1 torchaudio==0.10.0解决了，为加快速度使用了镜像源

**Comment by johnjim0816** [comment]
> 在window上配环境时，pip install torch==1.10.0 torchvision==0.11.1 torchaudio==0.10.0报错，改为pip install torch==1.10.0 torchvision==0.11.1 torchaudio==0.10.0解决了，为加快速度使用了镜像源

我更新一下readme，感谢
