### ISSUE TITLE
其他很多.yaml文件运行不了

### ISSUE THREAD

**Issue by zforward0** [datawhalechina/joyrl#9]
作者你好，我想知道为什么我将.yaml文件为preset里的其他文件之后，运行会一直出错。难道只能运行你给的例子吗？其他的很多.yaml文件都运行不了

**Comment by johnjim0816** [comment]
> 作者你好，我想知道为什么我将.yaml文件为preset里的其他文件之后，运行会一直出错。难道只能运行你给的例子吗？其他的很多.yaml文件都运行不了

目前还处于开发迁移阶段，很多几个月前更新的yaml文件都是上个版本跑通的，所以到这个版本会有一些参数没有对齐的问题，你可以告诉我你想跑的yaml，我们会第一时间更新，否则没有需求的情况下我们计划先扩充算法库再迭代掉所有的yaml

**Comment by zforward0** [comment]
作者你好，我想跑Pendulum-v1_TD3_mp_Train.yaml，Pendulum-v1_TD3_mp_Test.yaml，还有CartPole-v1文件夹里的yaml文件。这个改参数需要怎么改，有的yaml文件里的env_cfg:new_step_api: true，一运行就显示是多余的参数，但是去掉也运行不了。另外我想问一下，那个gym软件包用的是从pip下载的还是joyrl-main\joyrl\envs\gym里的

发件人：johnjim0816 ***@***.***>
发送日期：2024-02-23 21:57:41
收件人：datawhalechina/joyrl ***@***.***>
抄送人：Feng Zhou ***@***.***>,Author ***@***.***>
主题：Re: [datawhalechina/joyrl] 其他很多.yaml文件运行不了 (Issue #9)

作者你好，我想知道为什么我将.yaml文件为preset里的其他文件之后，运行会一直出错。难道只能运行你给的例子吗？其他的很多.yaml文件都运行不了
目前还处于开发迁移阶段，很多几个月前更新的yaml文件都是上个版本跑通的，所以到这个版本会有一些参数没有对齐的问题，你可以告诉我你想跑的yaml，我们会第一时间更新，否则没有需求的情况下我们计划先扩充算法库再迭代掉所有的yaml

**Comment by johnjim0816** [comment]
> 作者你好，我想跑Pendulum-v1_TD3_mp_Train.yaml，Pendulum-v1_TD3_mp_Test.yaml，还有CartPole-v1文件夹里的yaml文件。这个改参数需要怎么改，有的yaml文件里的env_cfg:new_step_api: true，一运行就显示是多余的参数，但是去掉也运行不了。另外我想问一下，那个gym软件包用的是从pip下载的还是joyrl-main\joyrl\envs\gym里的 发件人：johnjim0816 ***@***.***> 发送日期：2024-02-23 21:57:41 收件人：datawhalechina/joyrl ***@***.***> 抄送人：Feng Zhou ***@***.***>,Author ***@***.***> 主题：Re: [datawhalechina/joyrl] 其他很多.yaml文件运行不了 (Issue #9) 作者你好，我想知道为什么我将.yaml文件为preset里的其他文件之后，运行会一直出错。难道只能运行你给的例子吗？其他的很多.yaml文件都运行不了 目前还处于开发迁移阶段，很多几个月前更新的yaml文件都是上个版本跑通的，所以到这个版本会有一些参数没有对齐的问题，你可以告诉我你想跑的yaml，我们会第一时间更新，否则没有需求的情况下我们计划先扩充算法库再迭代掉所有的yaml — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

这两个都有的, 在https://github.com/datawhalechina/joyrl/blob/main/presets/ClassControl/Pendulum-v1/Pendulum-v1_TD3.yaml，你说的文件忘了删了，下一个版本会删掉。gym的话参考requirements和readme
